### PR TITLE
Fix: Route matching with encoded paths

### LINKED ISSUE #281: Encoded paths are not supported
With this code 
```
object HelloWorldZHttpServer extends App {

    val app2 = Http.collect[Request] {
      case Method.GET -> Root / "greet" / name  => Response.text(s"Greetings $name!")
    }

  // starting the server
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    Server.start(8090, app2).exitCode
}
```

when I execute this request:

`GET http://localhost:8090/greet/apple%2Fred`

I get this output:
`The requested URI "/greet/apple%2Fred" was not found on this server`

but expected result is:
`Greetings apple/red!
`

### PR DESCRIPTION
**Pull request by ShrutiVerma97**
fixes #281

### CODE REVIEW

File: example/src/main/scala/HelloWorld.scala [hunk 1]
```diff
@@ -2,12 +2,15 @@ import zhttp.http._
...
+
 object HelloWorld extends App {
 
   // Create HTTP route
   val app: HttpApp[Any, Nothing] = HttpApp.collect {
-    case Method.GET -> Root / "text" => Response.text("Hello World!")
-    case Method.GET -> Root / "json" => Response.jsonString("""{"greetings": "Hello World!"}""")
+    case Method.GET -> Root / "text"         => Response.text("Hello World!")
+    case Method.GET -> Root / "json"         => Response.jsonString("""{"greetings": "Hello World!"}""")
+    case Method.GET -> Root / "greet" / name => Response.text(s"Greetings ${URLDecoder.decode(name, "UTF-8")}!")
```
Comment (tusharmath) [inline example/src/main/scala/HelloWorld.scala]: Undo changes in the example. Write a unit test to reproduce the issue.

**Review by tusharmath — APPROVED** [review]
