### PR TITLE
Fix: Binary WebSocketFrame

### LINKED ISSUE #1004: Using binary WebsocketFrame fails
**Describe the bug**
While using WebSockets, succeeding the stream with binary WebSocketFrame is returning error:
```io.netty.util.IllegalReferenceCountException: refCnt: 0```

**To Reproduce**
1. Create a Server
```scala
  private val socket =
    Socket.collect[WebSocketFrame] { case WebSocketFrame.Binary(buffer) =>
      ZStream(WebSocketFrame.binary(buffer))
    }

  private val app =
    Http.collectZIO[Request] { case Method.GET -> !! / "subscriptions" =>
      socket.toResponse
    }

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    Server.start(8090, app).exitCode
```
2. Create a Client
```scala
  // Setup client envs
  val env = EventLoopGroup.auto() ++ ChannelFactory.auto

  val url = "ws://localhost:8090/subscriptions"

  val app = Socket
    .collect[WebSocketFrame] { case _ =>
      ZStream.succeed(WebSocketFrame.close(1000))
    }
    .toSocketApp
    .onOpen(Socket.succeed(WebSocketFrame.binary(Unpooled.copiedBuffer("Hello", CharsetUtil.UTF_8))))
    .connect(url)

  override def run(args: List[String]): URIO[ZEnv, ExitCode] = {
    app.exitCode.provideCustomLayer(env)
  }
```
3. Run server and client.

**Expected behaviour**
It should return Binary Websocketframe on server side

### PR DESCRIPTION
**Pull request by girdharshubham**
Closes #1004

### CODE REVIEW

File: zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala [hunk 1]
```diff
@@ -32,4 +33,17 @@ object WebSocketServerSpec extends HttpRunnableSpec {
...
+  def websocketFrameSpec = suite("WebSocketFrameSpec") {
+    testM("binary") {
+      val socket: Socket[Any, Nothing, WebSocketFrame, WebSocketFrame] = Socket
+        .collect[WebSocketFrame] { case WebSocketFrame.Binary(buffer) =>
+          ZStream.succeed(WebSocketFrame.Binary(buffer))
+        }
+      val app                                                          = socket.toHttp.deployWS
+
+      val open = Socket.succeed(WebSocketFrame.binary(Chunk.fromArray("Hello, World".getBytes)))
+      assertM(app(socket.toSocketApp.onOpen(open)).map(_.status))(equalTo(Status.SWITCHING_PROTOCOLS))
```
Comment (girdharshubham) [inline zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala:46]: Trying to make this test better.

File: zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala [hunk 2]
```diff
@@ -32,4 +33,17 @@ object WebSocketServerSpec extends HttpRunnableSpec {
...
     }
   }
+
+  def websocketFrameSpec = suite("WebSocketFrameSpec") {
+    testM("binary") {
+      val socket: Socket[Any, Nothing, WebSocketFrame, WebSocketFrame] = Socket
+        .collect[WebSocketFrame] { case WebSocketFrame.Binary(buffer) =>
+          ZStream.succeed(WebSocketFrame.Binary(buffer))
+        }
+      val app                                                          = socket.toHttp.deployWS
```
Comment (tusharmath) [inline zio-http/src/test/scala/zhttp/service/WebSocketServerSpec.scala]:
```suggestion
      val socket = Socket.collect[WebSocketFrame] { case WebSocketFrame.Binary(buffer) =>
        ZStream.succeed(WebSocketFrame.Binary(buffer))
      }
        
      val app = socket.toHttp.deployWS
```

**Review by tusharmath — APPROVED** [review]
