### PR TITLE
 Fix: Endpoint fix in `to` operator

### LINKED ISSUE #729: composing endpoints doesn't work
**Describe the bug**
Combining endpoints isn't working as expected

**To Reproduce**
```scala
object Endpoints extends App {
  def h1 = GET / "a" / *[Int] / "b" / *[Boolean] to { a =>
    Response.text(a.params.toString)
  }

  def h2 = GET / "b" / *[Int] / "b" / *[Boolean] to { a =>
    Response.text(a.params.toString)
  }
  // Run it like any simple app
  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    Server.start(8091, h2 ++ h1).exitCode
}
```
```bash
GET /a/2/b/true // The requested URI "/a/2/b/true" was not found on this server
GET /b/2/b/true // (2,true)
```

**Expected behavior**
```bash
GET /a/2/b/true // (2, true)
GET /b/2/b/true // (2, true)
```

### PR DESCRIPTION
**Pull request by sumawa**
To resolve #729

### CODE REVIEW

File: zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala [hunk 1]
```diff
@@ -40,11 +41,12 @@ object CanConstruct {
         route: Endpoint[A],
         f: Request.ParameterizedRequest[A] => ZIO[R, E, Response[R, E]],
       ): HttpApp[R, E] =
-        Http.collectM[Request] { case req =>
-          route.extract(req) match {
-            case Some(value) => f(Request.ParameterizedRequest(req, value))
-            case None        => UIO(Response.fromHttpError(HttpError.NotFound(req.url.path)))
-          }
+        Http.collectM[Request] {
```
Comment (sumawa) [inline zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala]: test case missing for this path

File: zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala [hunk 2]
```diff
@@ -23,11 +23,12 @@ object CanConstruct {
...
 
     override def make(route: Endpoint[A], f: Request.ParameterizedRequest[A] => Response[R, E]): HttpApp[R, E] =
-      Http.collect[Request] { case req =>
-        route.extract(req) match {
-          case Some(value) => f(Request.ParameterizedRequest(req, value))
-          case None        => Response.fromHttpError(HttpError.NotFound(req.url.path))
-        }
+      Http.collect[Request] {
+        case req if route.extract(req).isDefined =>
+          route.extract(req) match {
```
Comment (amitksingh1490) [inline zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala]: Prevent extraction from happening twice

File: zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala [hunk 3]
```diff
@@ -61,6 +62,18 @@ object EndpointSpec extends DefaultRunnableSpec {
...
+        val a      = Method.GET / "a" / *[Int] to { _ => Response.ok }
+        val b      = Method.GET / "b" / *[Int] to { _ => Response.ok }
+        val actual = (a ++ b).execute(Request(Method.GET, URL(Path("/b/2")))).map(_.status)
+        assert(actual)(equalTo(HExit.succeed(Status.OK)))
+      } +
+      testM("combining endpoints should resolve second effect") {
+        val a      = Method.GET / "a" / *[Int] to { _ => UIO(Response.ok) }
+        val b      = Method.GET / "b" / *[Int] to { _ => UIO(Response.ok) }
+        val actual = (a ++ b).execute(Request(Method.GET, URL(Path("/b/2")))).map(_.status)
+        assertM(actual.toEffect)(equalTo(Status.OK))
```
Comment (tusharmath) [inline zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]: Write tests for `route` not `Http` here.

File: zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala (hunk 2 above)
Comment (amitksingh1490) [reply zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala]:
```scala
Http.collect[Request] { case req =>
          route.extract(req) match {
            case Some(value) => Http.succeed(f(Request.ParameterizedRequest(req, value)))
            case None        => Http.empty
          }
        }
        .flatten
```
Something like this might solve the issue. Don't know which one performs better. jmh benchmark might help here.
@tusharmath  Please suggest

File: zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala (hunk 3 above)
Comment (sumawa) [reply zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]: @tusharmath  I have added tests based on Http as it is about testing combining end points which results in an Http, like this:
```
val app: Http[Any, Nothing, Request, Response[Any, Nothing]] = endpoint1 ++ endpoint2
```
Should we stick to Http based assertions then?

File: zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala [hunk 4]
```diff
@@ -62,5 +62,16 @@ object EndpointSpec extends DefaultRunnableSpec {
         assert(route.extract(!! / "1"))(isNone) &&
         assert(route.extract(!! / "c"))(isNone)
       }
+  } + suite("Request to Response ") {
+    test("Failure to find endpoint should return HExit.empty") {
```
Comment (amitksingh1490) [inline zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]: Add positive test cases also

File: zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala [hunk 5]
```diff
@@ -62,5 +62,16 @@ object EndpointSpec extends DefaultRunnableSpec {
         assert(route.extract(!! / "1"))(isNone) &&
         assert(route.extract(!! / "c"))(isNone)
       }
+  } + suite("Request to Response ") {
```
Comment (amitksingh1490) [inline zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]:
```suggestion
  } + suite("to") {
```

File: zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala (hunk 4 above)
Comment (amitksingh1490) [inline zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]:
```suggestion
    test("Endpoint doesn't Match") {
```

File: zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala [hunk 6]
```diff
@@ -62,5 +62,16 @@ object EndpointSpec extends DefaultRunnableSpec {
...
+    test("Failure to find endpoint should return HExit.empty") {
+      val a      = Method.GET / "a" / *[Int] to { _ => Response.ok }
+      val actual = a.execute(Request(Method.GET, URL(Path("/b/2"))))
+      assert(actual)(isEmpty)
+    } +
+      test("Failure to find endpoint with effect should return HExit.empty") {
```
Comment (amitksingh1490) [inline zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]:
```suggestion
      test("Endpoint with effect doesn't match") {
```

File: zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala [hunk 7]
```diff
@@ -62,5 +62,16 @@ object EndpointSpec extends DefaultRunnableSpec {
...
+        val a      = Method.GET / "a" / *[Int] to { _ => zio.UIO(Response.ok) }
```
Comment (amitksingh1490) [inline zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]:
```suggestion
        val a      = Method.GET / "a" / *[Int] to { _ => UIO(Response.ok) }
```

File: example/src/main/scala/example/Endpoints.scala [hunk 8]
```diff
@@ -7,11 +7,15 @@ import zhttp.service.Server
 import zio.{App, ExitCode, URIO}
 
 object Endpoints extends App {
-  def app = GET / "a" / *[Int] / "b" / *[Boolean] to { a =>
+  def h1 = GET / "a" / *[Int] / "b" / *[Boolean] to { a =>
+    Response.text(a.params.toString)
+  }
+
+  def h2 = GET / "b" / *[Int] / "b" / *[Boolean] to { a =>
```
Comment (amitksingh1490) [inline example/src/main/scala/example/Endpoints.scala:14]: compose an app which returns an effect also

Comment (sumawa) [reply example/src/main/scala/example/Endpoints.scala:14]: done

File: zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala [hunk 9]
```diff
@@ -39,12 +41,15 @@ object CanConstruct {
       override def make(
         route: Endpoint[A],
         f: Request.ParameterizedRequest[A] => ZIO[R, E, Response[R, E]],
-      ): HttpApp[R, E] =
-        Http.collectZIO[Request] { case req =>
-          route.extract(req) match {
-            case Some(value) => f(Request.ParameterizedRequest(req, value))
-            case None        => UIO(Response.fromHttpError(HttpError.NotFound(req.url.path)))
+      ): HttpApp[R, E] = {
+        Http
```
Comment (amitksingh1490) [inline zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala:44]: New version has operator called `collectHttp` use that

File: zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala [hunk 10]
```diff
@@ -23,12 +23,14 @@ object CanConstruct {
     override type EOut = E
 
     override def make(route: Endpoint[A], f: Request.ParameterizedRequest[A] => Response[R, E]): HttpApp[R, E] =
-      Http.collect[Request] { case req =>
-        route.extract(req) match {
-          case Some(value) => f(Request.ParameterizedRequest(req, value))
-          case None        => Response.fromHttpError(HttpError.NotFound(req.url.path))
+      Http
```
Comment (amitksingh1490) [inline zio-http/src/main/scala/zhttp/endpoint/CanConstruct.scala:26]: New version has operator called `collectHttp` use that

File: zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala [hunk 11]
```diff
@@ -62,5 +63,26 @@ object EndpointSpec extends DefaultRunnableSpec {
...
+      } +
+      test("endpoint matches") {
+        val a   = Method.GET / "a" / *[Int] to { _ => Response.ok }
+        val app = a.execute(Request(Method.GET, URL(Path("/a/2"))))
+        assert(app.map(_.status))(isSuccess(equalTo(Status.OK)))
+      } +
+      test("endpoint with effect matches") {
+        val a   = Method.GET / "a" / *[Int] to { _ => UIO(Response.ok) }
+        val app = a.execute(Request(Method.GET, URL(Path("/a/2"))))
+        zio.test.assert(app.map(_.status))(isEffect)
```
Comment (amitksingh1490) [inline zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]: Do we need to map status? Its not getting matched any place.

Comment (amitksingh1490) [inline zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]:
```suggestion
        assert(app)(isEffect)
```

File: zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala [hunk 12]
```diff
@@ -62,5 +63,26 @@ object EndpointSpec extends DefaultRunnableSpec {
         assert(route.extract(!! / "1"))(isNone) &&
         assert(route.extract(!! / "c"))(isNone)
       }
+  } + suite("To") {
```
Comment (amitksingh1490) [inline zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]: A newline after +

**Review by amitksingh1490 — APPROVED** [review]

File: zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala [hunk 13]
```diff
@@ -62,5 +63,23 @@ object EndpointSpec extends DefaultRunnableSpec {
         assert(route.extract(!! / "1"))(isNone) &&
         assert(route.extract(!! / "c"))(isNone)
       }
-  }
+  } +
+    suite("To") {
+      testM("endpoint doesn't match") {
+        val app = Method.GET / "a" / *[Int] to { _ => Response.ok }
+        assertM(app(Request(url = URL(Path("/b/2")))).flip)(isNone)
```
Comment (amitksingh1490) [inline zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]:
```suggestion
        assertM(app(Request(url = URL(!!/b/2)))).flip)(isNone)
```

File: zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala [hunk 14]
```diff
@@ -62,5 +63,23 @@ object EndpointSpec extends DefaultRunnableSpec {
         assert(route.extract(!! / "1"))(isNone) &&
         assert(route.extract(!! / "c"))(isNone)
       }
-  }
+  } +
+    suite("To") {
```
Comment (tusharmath) [inline zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]:
```suggestion
    suite("to") {
```

File: zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala [hunk 15]
```diff
@@ -62,5 +63,23 @@ object EndpointSpec extends DefaultRunnableSpec {
...
+      testM("endpoint doesn't match") {
+        val app = Method.GET / "a" / *[Int] to { _ => Response.ok }
+        assertM(app(Request(url = URL(Path("/b/2")))).flip)(isNone)
+      } +
```
Comment (tusharmath) [inline zio-http/src/test/scala/zhttp/endpoint/EndpointSpec.scala]:
```suggestion
      testM("endpoint doesn't match") {
        val app = Method.GET / "a" / to { _ => Response.ok }
        assertM(app(Request(url = URL(!! / "b"))).flip)(isNone)
      } +
```
