### PR TITLE
Make QueryParams#unsafeQueryParam return null for missing key (#3441)

### LINKED ISSUE #3441: when an Endpoints implements function with options will only be called when all options are present
**Describe the bug**
I have an Endpoint that should have query params as Optional. If I do not specify all the query parameters that are optional, it will result in a 500. I have tried all combinations of @optionalField and Option[String] for the type.

**To Reproduce**
Steps to reproduce the behaviour:
```
final case class QueryParams(
    @optionalField
    language: String,
    @optionalField
    location: String
  )

val getInfo =
    Endpoint(Method.GET / "testEndpoint")
      .query[QueryParams]
      .out[String]
```

In this curl, only location is being passed, which results in a 500. If both location and language are passed, I will get a 200 and the `implements` function will be called.
```
curl -v -X 'GET' \
  'http://localhost:8080/testEndpoint?location=1' \
  -H 'accept: application/json' \


* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> GET /testEndpoint?location=1 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> accept: application/json
>
* Request completely sent off
< HTTP/1.1 500 Internal Server Error
< content-length: 0
```

**Expected behaviour**
I should get a 200 when the implements is called.

**Additional context**

### PR DESCRIPTION
**Pull request by 987Nabil**
fixes #3441

### CODE REVIEW

**Review by kyri-petrou — APPROVED** [review]

File: zio-http/shared/src/main/scala/zio/http/QueryParams.scala [hunk 1]
```diff
@@ -133,8 +133,10 @@ object QueryParams {
     override def updateQueryParams(f: QueryParams => QueryParams): QueryParams =
       f(self)
 
-    override private[http] def unsafeQueryParam(key: String): String =
-      underlying.get(key).get(0)
+    override private[http] def unsafeQueryParam(key: String): String = {
+      val value = underlying.get(key)
+      if (value == null) null else value.get(0)
```
Comment (mwalden) [inline zio-http/shared/src/main/scala/zio/http/QueryParams.scala]: given that this is a list, you are still open to throwing a null pointer.

**Comment by mwalden** [comment]
there were tests in the initial PR that were closed. to be safe, we should probably include them too.

https://github.com/zio/zio-http/pull/3443

File: zio-http/shared/src/main/scala/zio/http/QueryParams.scala (hunk 1 above)
Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/QueryParams.scala]: Why? If it is null, I return null. If it is the empty list, get 0 returns null. That is the behaviour I want. Did I miss something?

**Comment by 987Nabil** [comment]
The tests already exists in the RoundtripSpec. It was green, because the value was added when it is encoded as null. Now it is not added, and without the fix in QueryParams it fails

File: zio-http/shared/src/main/scala/zio/http/QueryParams.scala (hunk 1 above)
Comment (mwalden) [reply zio-http/shared/src/main/scala/zio/http/QueryParams.scala]: sorry i meant that on value.get(0). we may want a check around that. 
edit:
sorry did you say .get(0) would return null on an empty list? Wouldnt it return out of bounds?

Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/QueryParams.scala]: fixed
