### PR TITLE
Fixed #2373: don't propagate ReadTimeoutExceptions

### LINKED ISSUE #2373: Handle client idle timeout to prevent abundant logging
Applications that use the http client keep seeing logging every few minutes (using version 3.0.0-RC2+45-e3636f00-SNAPSHOT):
```
logger: "io.netty.channel.DefaultChannelPipeline"
message: "An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception."
stack_trace: "io.netty.handler.timeout.ReadTimeoutException: null"
```
They always comes in groups of 10 with just a few ms between them. There is never a request going on at that time. According to @vigoo the groups of 10 means that all connections in the connection pool time out at the same time (it has a default size of 10).

I would prefer not to have these warnings logged.

Of course, these warning could be suppressed using the logging framework, but handling this in zio-http gives a better developer experience for all users.

@vigoo suggests to handle the timeout so it does not get logged. Probably in the client inbound handler.

See [Discord discussion](https://discord.com/channels/629491597070827530/819703129267372113/1138129262973562880).

### PR DESCRIPTION
**Pull request by ekhov**
On idle timeout for NettyConnectionPool handle ReadTimeoutExceptions- just log them with debug level, so they don't propagate as unhandled errors further

#2373 
/claim #2373

### CODE REVIEW

File: project/Dependencies.scala [hunk 1]
```diff
@@ -16,6 +16,8 @@ object Dependencies {
 
   val scalafmt = "org.scalameta" %% "scalafmt-dynamic" % "3.7.17"
 
+  val `scala-logging` = "com.typesafe.scala-logging" %% "scala-logging"   % "3.9.5"
```
Comment (vigoo) [inline project/Dependencies.scala]: We should not depend on this library, ZIO has it's own built-in logging API

Comment (ekhov) [reply project/Dependencies.scala]: Used built-in logging

File: zio-http/src/main/scala/zio/http/netty/client/NettyConnectionPool.scala [hunk 2]
```diff
@@ -127,9 +125,24 @@ object NettyConnectionPool {
     } yield result
   }
 
+  private final class ReadTimeoutErrorHandler(nettyRuntime: NettyRuntime)(implicit trace: Trace)
+      extends ChannelInboundHandlerAdapter {
```
Comment (ekhov) [inline zio-http/src/main/scala/zio/http/netty/client/NettyConnectionPool.scala:129]: Also I had an idea of implementing `ReadTimeoutHandler` itself and rewrite `readTimedOut` method, so instead of raising an exception, it would just write a log message. But I'm not sure which way is more correct/idiomatic

**Review by jdegoes — APPROVED** [review]
