### PR TITLE
Release/next

### LINKED ISSUE #350: Incorrect behaviour of getBodyAsString
Seems that current implementation of `getBodyAsString` isn't able to extract let's say utf-8 chars from request body (as it simply converts every byte to a char, which is not the case when a symbol doesn't fit one byte). Maybe it's possible to extract somehow charset from headers and make a string using `String(byte bytes[], Charset charset)` constructor?

### LINKED ISSUE #423: Document an example demonstrating integration with twirl
# Description
Twirl is a powerful Scala-based template engine. We'd need a document and an example demonstrating integration of zio-http with twirl.

# Example
* A sample application
```scala
package edu.self.training

import play.twirl.api._
import zhttp.http._
import zhttp.service.Server
import zio.{ExitCode, URIO}

object ZIOHttp extends zio.App {
  val app: HttpApp[Any, Nothing] = HttpApp.collect {
    case Method.GET -> Root => {
      val response: UResponse = Response
        .text(html
          .index("John Doe", 42)
          .toString()
        )

      response
        .asInstanceOf[UHttpResponse]
        .copy(headers = List(Header.custom("content-type", "text/html")))
    }
  }

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    Server.start(80, app).exitCode

}
```
* Build configuration
```scala
project.enablePlugins(SbtTwirl)
```
* Plugin
```scala
addSbtPlugin("com.typesafe.sbt" % "sbt-twirl" % "1.5.1")
```

# Specs
* The example should be complex enough to demonstrate capabilities provided by Twirl and a ZIO-backed implementation of the templating process

### LINKED ISSUE #480: Move all the examples in an Example Package

### LINKED ISSUE #492: Re-look at function names for consistency.

### LINKED ISSUE #504: Handle 100 Continue Status Code

### LINKED ISSUE #512: Support for https in release/next

### PR DESCRIPTION
**Pull request by tusharmath**

### CODE REVIEW

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 17.02**

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 437875.70**

File: example/src/main/scala/example/ThreadSafety.scala [hunk 1]
```diff
@@ -0,0 +1,25 @@
+package example
```
Comment (amitksingh1490) [inline example/src/main/scala/example/ThreadSafety.scala]: Not needed

**Review by amitksingh1490 — APPROVED** [review]

**Comment by amitksingh1490** [comment]
## 🚀🚀🚀 Benchmark Results 
 **Concurrency: 256** 
 **Requests/sec: 434505.09**
