### PR TITLE
fix(Header): basic auth header fixed

### LINKED ISSUE #270: Incorrect value in header with Header.basicHttpAuthorization
Hello

When using [Header.basicHttpAuthorization()](https://github.com/dream11/zio-http/blob/8a1d1e374f8de31ddfe65b5f129fc5c314479036/zio-http/src/main/scala/zhttp/http/Header.scala#L54) the authorization header value should be separated by whitespace.
```
Header.basicHttpAuthorization("foo", "bar") // Header("authorization","Basic:Zm9vOmJhcg==")
// Should be Header("authorization","Basic Zm9vOmJhcg==")
```
Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization#examples 

Release: 1.0.0.0-RC17+8-8a1d1e37-SNAPSHOT

### PR DESCRIPTION
**Pull request by ShrutiVerma97**
fixes #270

### CODE REVIEW

File: zio-http/src/main/scala/zhttp/http/Header.scala [hunk 1]
```diff
@@ -51,7 +51,7 @@ object Header {
     val authString    = String.format("%s:%s", username, password)
     val authCB        = Unpooled.wrappedBuffer(authString.getBytes(CharsetUtil.UTF_8))
     val encodedAuthCB = Base64.encode(authCB)
-    val value         = String.format("%s:%s", BasicSchemeName, encodedAuthCB.toString(CharsetUtil.UTF_8))
+    val value         = String.format("%s %s", BasicSchemeName, encodedAuthCB.toString(CharsetUtil.UTF_8))
```
Comment (tusharmath) [inline zio-http/src/main/scala/zhttp/http/Header.scala:54]: can add some unit tests on this.

Comment (ShrutiVerma97) [reply zio-http/src/main/scala/zhttp/http/Header.scala:54]: Tests already added for `basicHttpAuthorization`. Do we need to add test cases for string format?

**Review by tusharmath — APPROVED** [review]
