### PR TITLE
fix(HelloWorld): backpressure example fixed

### LINKED ISSUE #509: Bug in HelloWorld backPressure example

### PR DESCRIPTION
**Pull request by ShrutiVerma97**
fixes #509

### CODE REVIEW

File: example/src/main/scala/example/HelloWorld.scala [hunk 1]
```diff
@@ -1,24 +1,24 @@
...
     }
   }
 
-  def h2 = HttpApp.fromHttp {
-    Http.collectM[Request] { case req =>
-      req.decodeContent(ContentDecoder.backPressure).map { content =>
-        Response(data = HttpData.fromStream(ZStream.fromChunkQueue(content)))
+  def h2 = HttpApp.collectM { case req @ Method.POST -> !! / "bar" =>
+    req.decodeContent(ContentDecoder.backPressure).map { content =>
+      req.getHeaderValue(HttpHeaderNames.CONTENT_LENGTH) match {
```
Comment (tusharmath) [inline example/src/main/scala/example/HelloWorld.scala]:
```suggestion
      req.getContentLength match {
```

File: zio-http/src/main/scala/zhttp/http/HeaderExtension.scala [hunk 2]
```diff
@@ -60,6 +60,9 @@ private[zhttp] trait HeaderExtension[+A] { self: A =>
   final def getContentType: Option[String] =
     getHeaderValue(HttpHeaderNames.CONTENT_TYPE)
 
+  final def getContentLength: Option[String] =
```
Comment (tusharmath) [inline zio-http/src/main/scala/zhttp/http/HeaderExtension.scala]:
```suggestion
  final def getContentLength: Option[Long] =
```

File: zio-http/src/main/scala/zhttp/http/Response.scala [hunk 3]
```diff
@@ -29,13 +29,13 @@ case class Response[-R, +E] private (
   /**
    * Extracts the length of the content specified in the response data.
    */
-  def getContentLength: Option[Long] = self.data.size
+  def getHttpDataSize: Option[Long] = self.data.size
 
   /**
    * Automatically detects the size of the content and sets it
    */
   def setPayloadHeaders: Response[R, E] = {
```
Comment (tusharmath) [inline zio-http/src/main/scala/zhttp/http/Response.scala]: can delete this function.

File: example/src/main/scala/example/HelloWorld.scala [hunk 4]
```diff
@@ -7,18 +7,17 @@ import zio.{App, ExitCode, URIO}
 
 object HelloWorld extends App {
 
-  def h1 = HttpApp.fromHttp {
-    Http.collectM[Request] { case req =>
-      req.decodeContent(ContentDecoder.text).map { content =>
-        Response(data = HttpData.fromText(content))
-      }
+  def h1 = HttpApp.collectM { case req @ Method.POST -> !! / "foo" =>
```
Comment (tusharmath) [inline example/src/main/scala/example/HelloWorld.scala]: - Move this to another example file.
- Checkout the version from main back.
