### PR TITLE
Handle content new lines in `fromFormAST` (#2976)

### LINKED ISSUE #2976: CRLF stripped in TextFields inside Multipart request
zio-http unexpectedly stripped CRLF inside TextField parts in multipart/form-data requests.
We are using config with request streaming enabled, other settings are default.
It happens with actual csv files which are uploaded via browser on our production code.

Given snippet reproducing the issue

```scala
//> using dep "dev.zio::zio:2.1.6"
//> using dep "dev.zio::zio-streams:2.1.6"
//> using dep "dev.zio::zio-http:3.0.0-RC9"

import zio.*
import zio.http.*

object ZioHttpIssue extends zio.ZIOAppDefault:

  def myhandler = handler { (req: Request) => 
      for {
        form <- req.body.asMultipartFormStream
        data <- form.fields.mapZIO { field =>
          field.asChunk
        }.runCollect
        text = data.head
      } yield text.asString
  }

  def mkBody(csv: String) = Body.fromMultipartFormUUID(
                      Form(
                        FormField.textField(
                          name = "csv_here",
                          value = csv,
                          mediaType = MediaType.forContentType("text/csv").get
                        )
                      )
                    )
  def run = {
    val dataCRLF = "1,2\r\n3,4\r\n"
    val dataLF = "1,2\n3,4\n"
    for {
      bodyCRLF <- mkBody(dataCRLF)
      bodyLF <- mkBody(dataLF)
      resultCRLF <- myhandler(Request.post("/", bodyCRLF))
      resultLF <- myhandler(Request.post("/", bodyLF))
      _ <- ZIO.whenDiscard(resultCRLF != dataCRLF) { 
        ZIO.succeed(println(s"For \\r\\n in body we got stripped it, given $resultCRLF, expected: $dataCRLF"))
      }
      _ <- if (resultLF == dataLF) 
        ZIO.succeed(println(s"For \\n in body we are good."))
        else ZIO.fail(new RuntimeException("For \\n in body we are not good too."))

      _ <- ZIO.fail(new RuntimeException("assertTrue(resultCRLF == dataCRLF)")).when(resultCRLF != dataCRLF)
    } yield ()
  }
```

### PR DESCRIPTION
**Pull request by 987Nabil**
fixes #2976
/claim #2976

### CODE REVIEW

File: zio-http/shared/src/main/scala/zio/http/FormField.scala [hunk 1]
```diff
@@ -159,6 +159,8 @@ object FormField {
       ) {
         case (accum, header: FormAST.Header) if header.name.equalsIgnoreCase("Content-Disposition")       =>
           (Some(header), accum._2, accum._3, accum._4)
+        case (accum, FormAST.EoL)                                                                         =>
+          (accum._1, accum._2, accum._3, accum._4 :+ FormAST.Content(Chunk[Byte](13, 10)))
```
Comment (narma) [inline zio-http/shared/src/main/scala/zio/http/FormField.scala]:
```suggestion
          (accum._1, accum._2, accum._3, accum._4 :+ FormAST.Content(FormAST.EoL.bytes))
```

To prevent Chunk creation every time, I suggest re-use it from `FormAST.EoL`

**Review by jdegoes — APPROVED** [review]

**Comment by narma** [comment]
Thanks!
