### PR TITLE
Remove warning header; Configurable generated error responses (#2955)

### LINKED ISSUE #2701: Why is warning header added by default?
I've noticed that the apps using ZIO HTTP send a warning header on error, containing some information about the backend implementation details (it explicitly mentions ZIO HTTP).

ScalaCLI example:
```scala
//> using scala 3.3.1
//> using dep dev.zio::zio-http:3.0.0-RC4

import zio.*
import zio.http.*

object Application extends ZIOAppDefault:

  private val routes =
    Method.GET / "test" -> Handler.internalServerError

  override def run =
    Server
      .serve(
        // this will remove the "warning" header if the route above is hit
        // in case of "not found" the "warning" header is added anyway
        routes.toHttpApp @@ Middleware.removeHeader("warning")
      )
      .provide(
        Server.defaultWithPort(8080)
      )
```

Some responses:
```bash
$ curl -v localhost:8080/test # no "warning" header - good
…
< HTTP/1.1 500 Internal Server Error
< content-length: 0
…
$ curl -v localhost:8080/notexists # "warning" header is present, not what I want
…
< HTTP/1.1 404 Not Found
< warning: 404 ZIO HTTP /notexists
< content-length: 0
…
```

Exposing backend implementation details (as I've said, this header mentions ZIO HTTP) can be considered a security issue. Moreover, if I'm not mistaken, the warning header is deprecated or soon to be deprecated (https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-cache-06#section-5.5).

After reading the documentation and looking for similar issues on GitHub I still don't  know how to get rid of these headers.

Is there a reason why this is the default behaviour, not opt-in? Is it possible to opt-out? I think such headers shouldn't be added by default.

I understand that I'm expressing a personal opinion, not a proper technical issue; however, I thought that it's worth raising anyway, as the answer may serve as a future reference, in case someone has a similar problem.

### LINKED ISSUE #2948: Warning header loses original exception when that exception contains invalid-for-netty-headers characters
**Describe the bug**
I am using zio-http and quill to build a REST service. I create a request handler via `Handler.fromFunctionZIO` that calls into my DB via a quill. In one instance, I forgot to `lift` a variable when creating the query (ie I did `id == someId` instead of `id == lift(someId)`. This causes quill to throw an `IllegalStateException` which is then treated as a fatal defect by the quill-created (I think? I don't think that's a relevant detail) ZIO instance. With `sandbox` turned on for my routes, the error handling mechanism attempts to turn the error into a warning response header. However, the error text for the `IllegalStateException` exception has a `\n` character in it, which fails netty's header validation (`verifyValidHeaderValueCharSequence` in `HttpHeaderValidationUtil.java` returns the index of the first `\n` in the string and not `-1`), causing the original error to be swallowed, and the warning response header to then contain the self-fulfilling meta Schrodinger's error `Validation failed for header 'warning'`. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Turn on sandbox (`Server.serve(routes.sandbox)`)
2. Call a route handled by a ZIO via `Handler.fromFunctionZIO`
3. Have this ZIO fail fatally, and include a new line character in the exception error message

**Expected behaviour**
The original error is returned in the warning header.

### LINKED ISSUE #2955: Remove internal usage of warning header
The warning header is currently used by zio-http. But is deprecated. I think errors should not add any info about stack traces or error messages in headers at all.
We should have error messages as opt-in in the body.
This should be a setting that can be set globally by a config, as well as by the user for a specific call to `Response.error` and similar methods.

### PR DESCRIPTION
**Pull request by 987Nabil**
* I removed the typed warning header code. The intention is, to not encourage usage of a deprecated header.
* I redesigned how error messages are created if generated from `Throwable` through internal code and certain user calls, like `sandbox`. The basic idea is, that the user can auto generate error responses and based on config the details are shown or not. The config is saved in a fiber ref. That makes it possible to not only set a global default, but override config based on the route or even the request. I added for that some middleware to support this in an easy way. For example, the following code will change the config based on a set header, to get maximum details for the error.
```scala
myRoute @@ ErrorResponseConfig.debug.whenHeader(_.get("zio-debug").contains("true"))
```
* By default, the generated error responses only have a status code.
* The error response will be in HTML, JSON or plaintext, based on the accept header^
 
fixes #2955
fixes #2701
fixes #2948

/claim #2955
/claim #2701
/claim #2948

### CODE REVIEW

File: zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala [hunk 1]
```diff
@@ -80,7 +80,10 @@ private[zio] final case class ServerInboundHandler(
         try {
           if (jReq.decoderResult().isFailure) {
             val throwable = jReq.decoderResult().cause()
-            attemptFastWrite(ctx, Response.fromThrowable(throwable))
+            attemptFastWrite(
+              ctx,
+              Response.fromThrowable(throwable, runtime.unsafeRunSync(ErrorResponseConfig.configRef.get)),
```
Comment (kyri-petrou) [inline zio-http/jvm/src/main/scala/zio/http/netty/server/ServerInboundHandler.scala]: It seems a bit wasteful to start a fiber only to extract a `FiberRef` from it.

How about adding this method to `NettyRuntime`:

```scala
def getRef[A](ref: FiberRef[A]): A = zioRuntime.fiberRefs.getOrDefault(ref)
```

And then this becomes:
```scala
Response.fromThrowable(throwable, runtime.getRef(ErrorResponseConfig.configRef))
```

File: zio-http/shared/src/main/scala/zio/http/Response.scala [hunk 2]
```diff
@@ -58,6 +58,9 @@ final case class Response(
         self.copy(body = Body.fromChunk(bytes))
       }
 
+  def contentType(json: MediaType): Response =
+    self.addHeader(Header.ContentType(json))
```
Comment (kyri-petrou) [inline zio-http/shared/src/main/scala/zio/http/Response.scala]: Rendering of the `ContentType` header is quite expensive. For this reason, at the bottom of the the `Response` companion object the main 3 content-types are cached after calling `untyped` on them (which invokes the `render` method).

Might be better to pattern match here and check if the media type here matches one of those 3 and use the cached value or fallback to `Header.ContentType.apply` if not?

Comment (kyri-petrou) [reply zio-http/shared/src/main/scala/zio/http/Response.scala]: Also the param name should be changed to `mediaType`

Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/Response.scala]: Maybe it is just the best to use the untyped API. Probably the cheapest.

File: zio-http/shared/src/main/scala/zio/http/ErrorResponseConfig.scala [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+ *   if true, includes the stack trace in the response body
+ * @param maxStackTraceDepth
+ *   maximum number of stack trace lines to include in the response body. Set to
+ *   0 to include all lines.
+ */
+case class ErrorResponseConfig(
+  withErrorBody: Boolean = false,
+  withStackTrace: Boolean = false,
+  maxStackTraceDepth: Int = 10,
+  errorFormat: ErrorResponseConfig.ErrorFormat = ErrorResponseConfig.ErrorFormat.Html,
```
Comment (kyri-petrou) [inline zio-http/shared/src/main/scala/zio/http/ErrorResponseConfig.scala:20]: I'm thinking plaintext might make more sense as a default as it accounts for a wider range of usecases (APIs & serving user content)

File: zio-http/shared/src/main/scala/zio/http/ErrorResponseConfig.scala [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+    ErrorResponseConfig(withErrorBody = true, withStackTrace = true, maxStackTraceDepth = 0)
+
+  lazy val debug: HandlerAspect[Any, Unit] =
+    Middleware.runBefore(configRef.set(debugConfig))
+
+  def withConfig(config: ErrorResponseConfig): HandlerAspect[Any, Unit] =
+    Middleware.runBefore(configRef.updateSome { case oldConfig if oldConfig != config => config })
+
+  private[http] lazy val configRef: FiberRef[ErrorResponseConfig] =
+    FiberRef.unsafe.make(ErrorResponseConfig())(Unsafe)
```
Comment (kyri-petrou) [inline zio-http/shared/src/main/scala/zio/http/ErrorResponseConfig.scala]: For performance reasons, `FiberRefs` use reference equality to determine whether a `FiberRef` was changed. It's probably not an issue but perhaps use `default` here _just incase_

File: zio-http/shared/src/main/scala/zio/http/Handler.scala [hunk 5]
```diff
@@ -746,10 +746,49 @@ object Handler extends HandlerPlatformSpecific with HandlerVersionSpecific {
...
   def error(status: => Status.Error, message: => String): Handler[Any, Nothing, Any, Response] =
-    fromResponse(Response.error(status, message))
+    (fromResponse(Response.status(status)) @@ Middleware.interceptHandlerStateful(
+      handler((req: Request) => (req.header(Header.Accept), (req, ()))),
+    ) {
+      handler { (accept: Option[Header.Accept], res: Response) =>
+        ErrorResponseConfig.configRef.get.map { cfg =>
+          if (cfg.withErrorBody) {
+            val mediaType: MediaType = accept
+              .flatMap(_.mimeTypes.sortBy(mt => -mt.qFactor.getOrElse(1.0)).map(_.mediaType).collectFirst {
```
Comment (kyri-petrou) [inline zio-http/shared/src/main/scala/zio/http/Handler.scala]: Should we add an implicit `Ordering` in the companion object of `Accept`? 🤔

File: zio-http/shared/src/main/scala/zio/http/Response.scala [hunk 6]
```diff
@@ -58,6 +58,9 @@ final case class Response(
         self.copy(body = Body.fromChunk(bytes))
       }
 
+  def contentType(mediaType: MediaType): Response =
+    self.addHeader("content-type", mediaType.fullType)
```
Comment (kyri-petrou) [inline zio-http/shared/src/main/scala/zio/http/Response.scala:64]: Outside the scope of this PR, but I'm wondering whether we should change the `fullType` to a `val` instead of a `lazy val` to avoid the penalty of lazy vals.

File: zio-http/shared/src/main/scala/zio/http/Response.scala [hunk 7]
```diff
@@ -206,21 +221,83 @@ object Response {
...
+
+  private def throwableToMessage(throwable: Throwable, status: Status, config: ErrorResponseConfig): Body =
+    if (!config.withErrorBody) Body.empty
+    else {
+      val stackTrace =
+        if (config.withStackTrace && throwable.getStackTrace.nonEmpty)
+          (if (config.maxStackTraceDepth == 0) throwable.getStackTrace
+           else throwable.getStackTrace.take(config.maxStackTraceDepth))
+            .mkString("\n", "\n", "")
+        else ""
```
Comment (kyri-petrou) [inline zio-http/shared/src/main/scala/zio/http/Response.scala]: Is `getStackTrace` cheap? Or should we rewrite this to invoke it only once?

File: zio-http/shared/src/main/scala/zio/http/Route.scala [hunk 8]
```diff
@@ -51,13 +51,13 @@ sealed trait Route[-Env, +Err] { self =>
...
   final def handleError(f: Err => Response)(implicit trace: Trace): Route[Env, Nothing] =
-    self.handleErrorCause(Response.fromCauseWith(_)(f))
+    self.handleErrorCauseZIO(c => ErrorResponseConfig.configRef.get.map(Response.fromCauseWith(c, _)(f)))
 
   final def handleErrorZIO(f: Err => ZIO[Any, Nothing, Response])(implicit trace: Trace): Route[Env, Nothing] =
     self.handleErrorCauseZIO { cause =>
       cause.failureOrCause match {
         case Left(err)    => f(err)
-        case Right(cause) => ZIO.succeed(Response.fromCause(cause))
+        case Right(cause) => ErrorResponseConfig.configRef.get.map(Response.fromCause(cause, _))
```
Comment (kyri-petrou) [inline zio-http/shared/src/main/scala/zio/http/Route.scala]: Not as nice, but it requires 1 FlatMap less:
```suggestion
        case Right(cause) => ErrorResponseConfig.configRef.getWith(c => ZIO.succeed(Response.fromCause(cause, c)))
```

There are a few other places this can be applied to

**Review by kyri-petrou — COMMENTED** [review]
Apologies, I missed some minor things in my last review. Otherwise LGTM

File: zio-http/shared/src/main/scala/zio/http/Response.scala (hunk 7 above)
Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/Response.scala]: I'll double check

File: zio-http/shared/src/main/scala/zio/http/Response.scala (hunk 6 above)
Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/Response.scala:64]: Since both are static strings, I'll expect the val to be cheap anyway

Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/Response.scala:64]: If this would be scala 3 only, inline def is probably best?

File: zio-http/shared/src/main/scala/zio/http/Handler.scala (hunk 5 above)
Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/Handler.scala]: We could also ensure it is always sorted.

File: zio-http/shared/src/main/scala/zio/http/Route.scala (hunk 8 above)
Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/Route.scala]: Still nice enough

File: zio-http/shared/src/main/scala/zio/http/ErrorResponseConfig.scala [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+ *
+ * @param withErrorBody
+ *   if true, includes the error message in the response body
+ * @param withStackTrace
+ *   if true, includes the stack trace in the response body
+ * @param maxStackTraceDepth
+ *   maximum number of stack trace lines to include in the response body. Set to
+ *   0 to include all lines.
+ */
+case class ErrorResponseConfig(
```
Comment (jdegoes) [inline zio-http/shared/src/main/scala/zio/http/ErrorResponseConfig.scala]:
```suggestion
final case class ErrorResponseConfig(
```

File: zio-http/shared/src/main/scala/zio/http/Handler.scala [hunk 10]
```diff
@@ -549,7 +547,7 @@ sealed trait Handler[-R, +Err, -In, +Out] { self =>
     self(in)
 
   final def sandbox(implicit trace: Trace): Handler[R, Response, In, Out] =
-    self.mapErrorCause(Response.fromCause(_))
+    self.mapErrorCauseZIO(c => ErrorResponseConfig.configRef.get.map(Response.fromCause(c, _)).flip)
```
Comment (jdegoes) [inline zio-http/shared/src/main/scala/zio/http/Handler.scala:550]: There's a fair amount of overhead here--of course, there was before, but now there is even more.

Could be useful to unsafely get the fiber ref value in as many places as you can "safely" bundle it up in lazy evaluation (like here).

File: zio-http/shared/src/main/scala/zio/http/Handler.scala (hunk 5 above)
Comment (jdegoes) [reply zio-http/shared/src/main/scala/zio/http/Handler.scala]: Best to ensure it's always sorted, we don't want to be doing this on each request.

Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/Handler.scala]: It has to be done on each request, since this the the requests accept header. But since the amount of accepted media types will be small, I thought a sorted list might be easier to understand. It is just sorted by q factor when ever you deal with the typed interface.

File: zio-http/shared/src/main/scala/zio/http/Response.scala (hunk 7 above)
Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/Response.scala]: I created a local val. I think we could optimize printing limited stack traces, since `getStackTrace` captures the full stack. We could probably walk the trace only until n. But I think this is okay for now.

File: zio-http/shared/src/main/scala/zio/http/Response.scala (hunk 6 above)
Comment (kyri-petrou) [reply zio-http/shared/src/main/scala/zio/http/Response.scala:64]: Let's tackle this in another issue/PR where we can revise the usages of `lazy val` in ZIO HTTP. I think there are quite a few unnecessary ones

Comment (kyri-petrou) [reply zio-http/shared/src/main/scala/zio/http/Response.scala:64]: https://github.com/zio/zio-http/issues/3051

File: zio-http/shared/src/main/scala/zio/http/Handler.scala (hunk 10 above)
Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/Handler.scala:550]: I tried to figure out, what you mean. But I don't get it.
Currently, this config is saved within a fiber ref. Therefore idk how to get it unsafe. Also idk if the call to sandbox needs to be that optimized? Don't we advertise this as a non-prod feature?
But what you try to say might be true for other places?

One other design option I thought of was, to use a ConcurrentHashMap with the route pattern as a key. That way we could avoid fiber refs and zio based access to our config storage.

File: zio-http/shared/src/main/scala/zio/http/Handler.scala (hunk 5 above)
Comment (jdegoes) [reply zio-http/shared/src/main/scala/zio/http/Handler.scala]: Maybe you could check and avoid sorting it if it's already sorted, which would avoid the overhead entirely for the happy path.

File: zio-http/shared/src/main/scala/zio/http/Handler.scala (hunk 10 above)
Comment (jdegoes) [reply zio-http/shared/src/main/scala/zio/http/Handler.scala:550]: Ah right, FiberRef instead of Ref.

Comment (jdegoes) [reply zio-http/shared/src/main/scala/zio/http/Handler.scala:550]: Wondering what the thought in using a fiber ref is? To make it compatible with scoped changes?

Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/Handler.scala:550]: Yes. That you can override the behavior per route/request.

**Review by jdegoes — APPROVED** [review]
