### PR TITLE
Response Json headers

### LINKED ISSUE #747: Wrong Header set in Response.json
**Describe the bug**
Response.json wrong header name, should be contentType

**Expected behavior**
contentType as a header name

### PR DESCRIPTION
**Pull request by amitksingh1490**
Fixes #747

### CODE REVIEW

File: zio-http/src/test/scala/zhttp/http/ResponseHelpersSpec.scala [hunk 1]
```diff
@@ -1,29 +1,31 @@
...
         } +
         test("Permanent redirect should produce a response with a location") {
-          val x = Response.redirect(location)
-          assert(x.getHeadersAsList)(contains(Headers.location(location)))
+          val x = Response.redirect(location, true)
+          assertTrue(x.getHeaderValue(HeaderNames.location).contains(location))
+        } +
+        test("Json should set content type to ApplicationJson") {
+          val x = Response.json("""{"message": "Hello"}""")
+          println(x.getHeadersAsList)
```
Comment (tusharmath) [inline zio-http/src/test/scala/zhttp/http/ResponseHelpersSpec.scala]:
```suggestion
```

**Review by tusharmath — APPROVED** [review]

File: zio-http/src/test/scala/zhttp/http/ResponseHelpersSpec.scala [hunk 2]
```diff
@@ -1,29 +1,30 @@
...
+object ResponseHelpersSpec extends DefaultRunnableSpec {
   val redirectSpec = {
     val location = "www.google.com"
     suite("redirectSpec")(
       test("Temporary redirect should produce a response with a TEMPORARY_REDIRECT") {
         val x = Response.redirect(location)
-        assert(x.status)(equalTo(Status.TEMPORARY_REDIRECT)) && assert(x.getHeadersAsList)(
-          contains(Headers.location(location)),
-        )
+        assertTrue(x.status == Status.TEMPORARY_REDIRECT && x.getHeaderValue(HeaderNames.location).contains(location))
```
Comment (tusharmath) [inline zio-http/src/test/scala/zhttp/http/ResponseHelpersSpec.scala]:
```suggestion
        assertTrue(x.status == Status.TEMPORARY_REDIRECT) && assertTrue(x.getHeaderValue(HeaderNames.location).contains(location))
```

**Review by tusharmath — CHANGES_REQUESTED** [review]
Some quick change.

**Comment by amitksingh1490** [comment]
> Some quick change.

Done

**Review by tusharmath — APPROVED** [review]
