### PR TITLE
fix: for escaping self closing tags

### LINKED ISSUE #708: In Html templating adding <script> tag without placeholder breaks the html
**Describe the bug**
Adding a <script> tag without a placeholder within Http.html causes closing body and html tag to appear within the script tag like this 

```
<head>
	<title>ZIO Http</title>
	<script src="https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js">
		</head>
			<body><div class="container text-align-left"><h1>Hello World</h1><10</a></li></ul></div>
			</body></html>
		</script>
</head>
```

**To Reproduce**
1. Go to 'example/src/main/scala/example/HtmlTemplating'
2. In the code  try both options shown below. 
```
html(
        // Support for child nodes
        head(
          title("ZIO Http"),
          // This one works
          //  script(srcAttr := "https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js", h2("placeholder")),
          // This doesn't work
          script(srcAttr := "https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js"),
        ),
        body(
        ),
      )
```
3. The first one generates the html correctly when accessed via browser  http://localhost:8090/hello/world/
4. The second one doesn't work in all 3 main browsers as the body elements are enclosed within the script element

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari, firefox]

**Additional context**
Here is the list of self closing tags, all other tags requires closing
http://xahlee.info/js/html5_non-closing_tag.html

### PR DESCRIPTION
**Pull request by girdharshubham**
#### An attempt at fixing issue #708.
Closes #708

### CODE REVIEW

File: zio-http/src/main/scala/zhttp/html/Dom.scala [hunk 1]
```diff
@@ -16,7 +16,7 @@ sealed trait Dom { self =>
       }
 
       if (elements.isEmpty && attributes.isEmpty) s"$doctype<$name/>"
```
Comment (girdharshubham) [inline zio-http/src/main/scala/zhttp/html/Dom.scala]: While debugging, the problem comes out here.
A quick/hacky way would be adding a `Element.selfClosingTags.contains(name))` bit in places where we generate self closing tags. But this would break existing cases wherein `<head />` is considered a valid test case.

Not sure if we want to break this support.
An updated list of self-closing tags: http://xahlee.info/js/html5_non-closing_tag.html

Comment (girdharshubham) [inline zio-http/src/main/scala/zhttp/html/Dom.scala]: Here as well.

File: zio-http/src/main/scala/zhttp/html/Elements.scala [hunk 2]
```diff
@@ -250,6 +250,9 @@ trait Elements {
 }
 
 object Element {
+  val selfClosingTags =
+    List(area, base, br, col, embed, hr, img, input, link, meta, param, source, track, wbr).map(_.name)
```
Comment (girdharshubham) [inline zio-http/src/main/scala/zhttp/html/Elements.scala]: Taken from: http://xahlee.info/js/html5_non-closing_tag.html

Comment (tusharmath) [reply zio-http/src/main/scala/zhttp/html/Elements.scala]: - Use a `Set` for better perf. 
- Use `String` and do a string comp.
- Add unit tests for self closing tags using Gen.
- Add unit tests for non-self closing tags using Gen.
- Add scala doc, for — What self closing tags are, and put the link.

File: zio-http/src/main/scala/zhttp/html/Elements.scala [hunk 3]
```diff
@@ -250,6 +250,9 @@ trait Elements {
 }
 
 object Element {
+  val voidElements: Set[String] =
```
Comment (tusharmath) [inline zio-http/src/main/scala/zhttp/html/Elements.scala]:
```suggestion
  private [zhttp] val voidElements: Set[String] =
```

File: zio-http/src/test/scala/zhttp/internal/ElementGen.scala [hunk 4]
```diff
@@ -0,0 +1,134 @@
+package zhttp.internal
+
+import zhttp.html._
+import zio.test.Gen
+
+object ElementGen extends Elements {
```
Comment (tusharmath) [inline zio-http/src/test/scala/zhttp/internal/ElementGen.scala]:
```suggestion
object DomGen {
```

File: zio-http/src/test/scala/zhttp/internal/ElementGen.scala [hunk 5]
```diff
@@ -0,0 +1,134 @@
...
+    track,
+    tt,
+    u,
+    ul,
+    variable,
+    video,
+    wbr,
+  ).map(_.name)
+
+  val notVoid: Gen[Any, String] = Gen.fromIterable(elements.filterNot(Element.voidElements))
```
Comment (tusharmath) [inline zio-http/src/test/scala/zhttp/internal/ElementGen.scala]: Use `Gen.anyString.filter(e => !Element.voidElements.contains(e))`

File: zio-http/src/test/scala/zhttp/internal/ElementGen.scala [hunk 6]
```diff
@@ -0,0 +1,134 @@
...
+  val void: Gen[Any, String]    = Gen.fromIterable(Element.voidElements)
```
Comment (tusharmath) [inline zio-http/src/test/scala/zhttp/internal/ElementGen.scala]:
```suggestion
  val void: Gen[Any, Dom]    = Gen.fromIterable(Element.voidElements)
```

Comment (girdharshubham) [reply zio-http/src/test/scala/zhttp/internal/ElementGen.scala]: Done.

File: zio-http/src/test/scala/zhttp/internal/ElementGen.scala (hunk 4 above)
Comment (girdharshubham) [reply zio-http/src/test/scala/zhttp/internal/ElementGen.scala]: Moved it to HttpGen

File: zio-http/src/test/scala/zhttp/internal/HttpGen.scala [hunk 7]
```diff
@@ -9,6 +10,8 @@ import zio.stream.ZStream
 import zio.test.{Gen, Sized}
 
 object HttpGen {
+  private def toDom(s: String): Dom = Dom.element(s)
```
Comment (tusharmath) [inline zio-http/src/test/scala/zhttp/internal/HttpGen.scala]: Why wrap a function into a method?

File: zio-http/src/test/scala/zhttp/html/DomSpec.scala [hunk 8]
```diff
@@ -62,23 +62,34 @@ object DomSpec extends DefaultRunnableSpec {
...
+          }
+      } + suite("Void Elements") {
+        testM("void") {
+          checkAll(HttpGen.voidDom) { dom =>
+            val name = dom.asInstanceOf[Dom.Element].name
+            assertTrue(dom.encode == s"<${name}/>")
           }
+        } + testM("not void") {
+          checkAll(HttpGen.notVoidDom) { dom =>
+            val name = dom.asInstanceOf[Dom.Element].name
```
Comment (tusharmath) [inline zio-http/src/test/scala/zhttp/html/DomSpec.scala]: don't use `asInstanceOf` find an alternative approach.

File: zio-http/src/test/scala/zhttp/internal/HttpGen.scala (hunk 7 above)
Comment (girdharshubham) [reply zio-http/src/test/scala/zhttp/internal/HttpGen.scala]: ~It will be taken as a function during eta-expansion.~
Done.

File: zio-http/src/test/scala/zhttp/html/DomSpec.scala [hunk 9]
```diff
@@ -62,22 +62,32 @@ object DomSpec extends DefaultRunnableSpec {
...
             val dom = Dom.element("html", Dom.element("head"))
-            assert(dom.encode)(equalTo("""<!DOCTYPE html><html><head/></html>"""))
+            assertTrue(dom.encode == """<!DOCTYPE html><html><head></head></html>""")
           } +
           test("with children and text") {
             val dom = Dom.element("html", Dom.element("head"), Dom.text("abc"))
-            assert(dom.encode)(equalTo("""<!DOCTYPE html><html><head/>abc</html>"""))
+            assertTrue(dom.encode == """<!DOCTYPE html><html><head></head>abc</html>""")
+          }
+      } + suite("VoidElements") {
```
Comment (amitksingh1490) [inline zio-http/src/test/scala/zhttp/html/DomSpec.scala]: `Nitpicking` :-p please move the suite to next line

Comment (girdharshubham) [reply zio-http/src/test/scala/zhttp/html/DomSpec.scala]: Done.

**Review by tusharmath — APPROVED** [review]
