### PR TITLE
Fix: EncodeClientParams

### LINKED ISSUE #867: HTTP requests contain malformed path
**Describe the bug**
On 1.0.0.0-RC22, we noticed that HTTPS requests succeed, and that HTTP requests (non-secure) fail. By digging deeper, we found that the HTTP commands are malformed during a normal HTTP request.

**To Reproduce**
1. Run netcat `nc -l 9000`
2. Run 

```scala
import zhttp.service.{ChannelFactory, Client, EventLoopGroup}
import zio.{App, ExitCode, URIO, console}

object SimpleClient extends App {

  val program = for {
    res <- Client.request("http://localhost:9000/foo")
    data <- res.getBodyAsString
    _ <- console.putStrLn(data)
  } yield ()

  override def run(args: List[String]): URIO[zio.ZEnv, ExitCode] =
    program.exitCode.provideCustomLayer(ChannelFactory.auto ++ EventLoopGroup.auto())
}
```
3. Go back to netcat and see that it received `GET http://localhost:9000/foo HTTP/1.1`
4. Confirm that we see `http://localhost:9000/foo` (observed) for a path instead of `/foo` (expected)

**Expected behavior**
That a HTTP request does `GET /foo HTTP/1.1` instead of `GET http://localhost:9000/foo HTTP/1.1`

**Desktop (please complete the following information):**
 - OS: MacOS 11.6

### PR DESCRIPTION
**Pull request by ShrutiVerma97**
fixes #867

### CODE REVIEW

File: zio-http/src/test/scala/zhttp/http/EncodeClientRequestSpec.scala [hunk 1]
```diff
@@ -38,13 +38,13 @@ object EncodeClientRequestSpec extends DefaultRunnableSpec with EncodeClientPara
...
           val req = encodeClientParams(HttpVersion.HTTP_1_1, params)
-          assert(req.uri())(equalTo(params.url.asString))
+          assert(req.uri())(equalTo(params.url.relative.asString))
         }
       } +
       testM("uri on HttpData.File") {
         check(HttpGen.clientParamsForFileHttpData()) { params =>
           val req = encodeClientParams(HttpVersion.HTTP_1_1, params)
-          assert(req.uri())(equalTo(params.url.asString))
+          assert(req.uri())(equalTo(params.url.relative.asString))
```
Comment (tusharmath) [inline zio-http/src/test/scala/zhttp/http/EncodeClientRequestSpec.scala]: Let's tests with actual and expected urls. Here we are testing implementation details.

**Review by tusharmath — APPROVED** [review]
