### PR TITLE
fix OpenAPI doc for Endpoint not rendered

### LINKED ISSUE #3045: [OpenAPI] The doc passed to  `Endpoint::out[A](doc = ...)` are not rendered
Reproducer:
```scala
val testEndpoint = 
  (Endpoint(RoutePattern.POST / "test") ?? Doc.p("This is my 'POST /test' endpoint doc"))
    .in[String](doc = Doc.p("this is the input doc"))
    .out[String](mediaType = MediaType.application.json, doc = Doc.p("this is the output doc"))

val spec: String =
  OpenAPIGen.fromEndpoints(
    title = "This is my OpenAPI doc title",
    version = "0.0.0",
    endpoints = List(testEndpoint)
  ).toJson
  
spec.contains("this is the output doc") // == false
```

### PR DESCRIPTION
**Pull request by geeeezmo**
As per [OpenAPI 3.0.3 spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md), `description` field for responses should be nested under status code (e.g. `responses.200`).
Components may have a `description` field, but it is not described for `schema` part by the official spec.

Also, eliminated merging of output documentation into `Endpoint` documentation when calling `.outX` family of endoint methods.

Resolves #3045

### CODE REVIEW

File: zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala [hunk 1]
```diff
@@ -609,10 +609,10 @@ final case class Endpoint[PathInput, Input, Err, Output, Auth <: AuthType](
     Endpoint(
       route,
       input,
-      output = ((HttpCodec.content[Output2](mediaType) ++ StatusCodec.status(status)) ?? doc) | self.output,
+      output = (HttpCodec.content[Output2](mediaType) ++ StatusCodec.status(status) ?? doc) | self.output,
```
Comment (987Nabil) [inline zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala]: As far as I can tell, this has either no effect on the codec or applies the doc only to status. In either way, I'd prefer to keep this. Unless you can tell me why that would turn tests read.

**Review by 987Nabil — CHANGES_REQUESTED** [review]

File: zio-http/jvm/src/test/scala/zio/http/endpoint/openapi/OpenAPIGenSpec.scala [hunk 2]
```diff
@@ -165,7 +165,7 @@ object OpenAPIGenSpec extends ZIOSpecDefault {
       (GET / "static" / int("id") / uuid("uuid") ?? Doc.p("user id") / string("name")) ?? Doc.p("get path"),
     )
       .in[SimpleInputBody](Doc.p("input body"))
-      .out[SimpleOutputBody](Doc.p("output body"))
+      .out[SimpleOutputBody](mediaType = MediaType.application.json, Doc.p("output body"))
```
Comment (987Nabil) [inline zio-http/jvm/src/test/scala/zio/http/endpoint/openapi/OpenAPIGenSpec.scala:168]: Why?

**Comment by jivanic-demystdata** [comment]
@geeeezmo Thanks for fixing this issue. I tried yesterday but couldn't find where the source of the issue was.
You'll have to rebase your branch on the `main` branch as we merged this branch: https://github.com/zio/zio-http/pull/3044, which renamed the `OpenAPI::doc` field to `OpenAPI::documentation`

File: zio-http/jvm/src/test/scala/zio/http/endpoint/openapi/OpenAPIGenSpec.scala (hunk 2 above)
Comment (guizmaii) [reply zio-http/jvm/src/test/scala/zio/http/endpoint/openapi/OpenAPIGenSpec.scala:168]: Probably to test this: https://github.com/zio/zio-http/pull/3044#discussion_r1726522056, which he also fixes in his PR here: https://github.com/zio/zio-http/pull/3046/files#diff-70f00f4d860129984cdbd655e9ea96e1c0b74ba77457b8a95a546a39739c1d96R578

**Comment by guizmaii** [comment]
FYI, I tested it on my project and it does fix the issue I reported :)

File: zio-http/jvm/src/test/scala/zio/http/endpoint/openapi/OpenAPIGenSpec.scala (hunk 2 above)
Comment (geeeezmo) [reply zio-http/jvm/src/test/scala/zio/http/endpoint/openapi/OpenAPIGenSpec.scala:168]: Yes, this is to test the exact issue described in #3044

File: zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala (hunk 1 above)
Comment (geeeezmo) [reply zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala]: You're right, this and the other change in `Endpoint` seem to have no effect on the codec - the tests are still green with the old code.
I think I was just playing around, trying to find the culprit, and thought this was it 😅

File: zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala [hunk 3]
```diff
@@ -575,7 +575,7 @@ final case class Endpoint[PathInput, Input, Err, Output, Auth <: AuthType](
       output = ((HttpCodec.content[Output2] ++ StatusCodec.status(status)) ?? doc) | self.output,
       error,
       codecError,
-      documentation,
+      self.documentation,
```
Comment (987Nabil) [inline zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala]: the self is now not needed anymore

File: zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala [hunk 4]
```diff
@@ -662,7 +662,7 @@ final case class Endpoint[PathInput, Input, Err, Output, Auth <: AuthType](
     alt: Alternator[Err2, Err],
   ): Endpoint[PathInput, Input, alt.Out, Output, Auth] =
     copy[PathInput, Input, alt.Out, Output, Auth](
-      error = ((ContentCodec.content[Err2]("error-response") ++ StatusCodec.status(status)) ?? doc) | self.error,
+      error = (ContentCodec.content[Err2]("error-response") ++ StatusCodec.status(status) ?? doc) | self.error,
```
Comment (987Nabil) [inline zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala]: you did not revert here

File: zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala [hunk 5]
```diff
@@ -794,7 +794,7 @@ final case class Endpoint[PathInput, Input, Err, Output, Auth <: AuthType](
     Endpoint(
       route,
       input,
-      output = ((contentCodec ++ StatusCodec.status(status)) ?? doc) | self.output,
+      output = (contentCodec ++ StatusCodec.status(status) ?? doc) | self.output,
```
Comment (987Nabil) [inline zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala]: same

File: zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala (hunk 3 above)
Comment (geeeezmo) [reply zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala]: Right, because the method parameter is still called `doc`.
Good catch, fixed

File: zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala (hunk 4 above)
Comment (geeeezmo) [reply zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala]: I did not revert, because that is exactly what causes the incorrect doc to be rendered - the `description` is placed under `schema` as well as under `responses.<CODE>`, which does not comply with the OpenAPI 3.0.3 spec.

Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala]: Then this is a bug in the generator. Not in the endpoint. The call is clearly: Set the content with that status and document the **whole**. The OpenAPI gen is then incorrectly adding the doc on the wrong place.
So even if this fixes the generated code, it is not the right fix.

Comment (geeeezmo) [reply zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala]: Right, OK, I'll take another look at it over the weekend.
Thanks for the review :)

Comment (geeeezmo) [reply zio-http/shared/src/main/scala/zio/http/endpoint/Endpoint.scala]: Found where the issue was.
Please, give this another review pass 😃

**Comment by guizmaii** [comment]
Oh fuckkkk! I pushed on your PR @geeeezmo. I'm really sorry. I'll fix that.

**Comment by guizmaii** [comment]
Oh. I'm really sorry @geeeezmo. I completely messed up. I overwrote your work. I'm so sorry. I was trying to push on another branch but didn't realise I was writing on yours.

Don't pull from the remote branch locally, that could erase your work.
Could you please overwrite what I did, please?
Maybe the simplest would be that we close this PR and you open a new one?

I'm so sorry again. I apologise for this. 🫣😟

**Comment by 987Nabil** [comment]
I guess [this](https://github.com/zio/zio-http/commit/8dbe505ee964b66aff31bddb5838284454960061) is the version that should be restored

**Comment by geeeezmo** [comment]
> Oh. I'm really sorry @geeeezmo. I completely messed up. I overwrote your work. I'm so sorry. I was trying to push on another branch but didn't realise I was writing on yours.
> 
> Don't pull from the remote branch locally, that could erase your work. Could you please overwrite what I did, please? Maybe the simplest would be that we close this PR and you open a new one?
> 
> I'm so sorry again. I apologise for this. 🫣😟

No worries 😆 
I've just force pushed from my local branch again

**Review by guizmaii — APPROVED** [review]
LGTM

**Review by 987Nabil — APPROVED** [review]
