### PR TITLE
[ZClient] Unsafely fulfil promises to avoid race conditions

### LINKED ISSUE #2841: ZClient - PrematureChannelClosureException
**Describe the bug**
`io.netty.handler.codec.PrematureChannelClosureException: Channel closed while executing the request. This is likely caused due to a client connection misconfiguration`  / `io.netty.handler.codec.PrematureChannelClosureException: channel gone inactive with 1 missing response(s)` when making simple HTTP GET requests

Note 10 second idleTimeout on the client config.

ZIO-HTTP-3.0.0-RC6

**To Reproduce**
```scala
package reproducer

import zio.http.*
import zio.*
import zio.http.netty.NettyConfig
import zio.durationInt

object ReproducerShortIdleTimeout extends ZIOAppDefault {

  override def run: ZIO[Any, Any, Unit] = {

    val appLogic = for {
      _ <- ZIO.logInfo("Starting HTTP server")

      routes = Routes(
        Method.GET / "sleep" / int("seconds") -> handler { (duration: Int, _: Request) =>
          ZIO.sleep(duration.seconds).as(Response.ok)
        },
        Method.GET / "makeSleepRequest" / int("seconds") -> handler { (seconds:Int, _: Request) =>
          for {
            _ <- ZIO.logInfo(s"Make Sleep Request: $seconds")
            client <- ZIO.service[ZClient[Any, Body, Throwable, Response]]
            _ <- ZIO.scoped {
              client.request(Request.get(s"http://127.0.0.1:8080/sleep/$seconds"))
                .tap {
                  response =>
                    ZIO.logInfo(s"Got response. Status: ${response.status.code} ")
                }
                .unit
                .catchAllCause {
                  cause =>
                    ZIO.logErrorCause(cause).unit
                }
            }
          } yield Response.ok
        }
      )

      port <- Server.install(routes.toHttpApp)
      _ <- ZIO.logInfo(s"Server started on port: $port")
      _ <- ZIO.never
    } yield ()

    val clientConfig = ZClient.Config.default.idleTimeout(10.seconds)
    val zClient = (ZLayer.succeed(clientConfig) ++ ZLayer.succeed(NettyConfig.defaultWithFastShutdown) ++ DnsResolver.default) >>> ZClient.live

    appLogic.provide(
      ZLayer.succeed(Server.Config.default.binding("0.0.0.0", 8080)),
      ZLayer.succeed(NettyConfig.default),
      zClient,
      Server.customized,
    ).catchAllCause(cause => ZIO.logErrorCause("Encountered an fatal error", cause))

  }

}
```

Making a GET Request to http://127.0.0.1:8080/makeSleepRequest/10 gives following output (no successful responses - sleep time equals idleTimeout):

```scala
timestamp=2024-05-13T10:46:04.255313800Z level=INFO thread=#zio-fiber-48 message="Make Sleep Request: 10" location=reproducer.Reproducer.run.appLogic.routes file=Reproducer.scala line=21
timestamp=2024-05-13T10:46:14.353016Z level=ERROR thread=#zio-fiber-48 message="" cause="Exception in thread "zio-fiber-48" io.netty.handler.codec.PrematureChannelClosureException: Channel closed while executing the request. This is likely caused due to a client connection misconfiguration
	at zio.http.netty.client.NettyClientDriver.requestOnChannel$$anonfun$1$$anonfun$2$$anonfun$2$$anonfun$1(NettyClientDriver.scala:171)
	at zio.ZIO$ZIOBooleanOps$.$amp$amp$extension$$anonfun$1(ZIO.scala:5186)
	at zio.ZIO$ZIOBooleanOps$.$amp$amp$extension$$anonfun$adapted$1(ZIO.scala:5186)
	at reproducer.Reproducer.run.appLogic.routes(Reproducer.scala:24)
	at reproducer.Reproducer.run.appLogic.routes(Reproducer.scala:28)
	at reproducer.Reproducer.run.appLogic.routes(Reproducer.scala:29)
	at reproducer.Reproducer.run.appLogic.routes(Reproducer.scala:33)
	at reproducer.Reproducer.run.appLogic.routes(Reproducer.scala:34)
	at reproducer.Reproducer.run.appLogic.routes(Reproducer.scala:35)" location=reproducer.Reproducer.run.appLogic.routes file=Reproducer.scala line=32
```

Making 3 subsequent GET Requests to http://127.0.0.1:8080/makeSleepRequest/4 (4 seconds sleep time) gives following output (first two requests are successful - third which goes past idleTimeout are not successful):

```scala
timestamp=2024-05-13T10:51:53.547703600Z level=INFO thread=#zio-fiber-48 message="Make Sleep Request: 4" location=reproducer.ReproducerShortIdleTimeout.run.appLogic.routes file=Reproducer.scala line=21
timestamp=2024-05-13T10:51:57.677798800Z level=INFO thread=#zio-fiber-48 message="Got response. Status: 200 " location=reproducer.ReproducerShortIdleTimeout.run.appLogic.routes file=Reproducer.scala line=27
timestamp=2024-05-13T10:51:59.265433100Z level=INFO thread=#zio-fiber-58 message="Make Sleep Request: 4" location=reproducer.ReproducerShortIdleTimeout.run.appLogic.routes file=Reproducer.scala line=21
timestamp=2024-05-13T10:52:03.291908800Z level=INFO thread=#zio-fiber-58 message="Got response. Status: 200 " location=reproducer.ReproducerShortIdleTimeout.run.appLogic.routes file=Reproducer.scala line=27
timestamp=2024-05-13T10:52:04.075285500Z level=INFO thread=#zio-fiber-73 message="Make Sleep Request: 4" location=reproducer.ReproducerShortIdleTimeout.run.appLogic.routes file=Reproducer.scala line=21
timestamp=2024-05-13T10:52:07.687879800Z level=ERROR thread=#zio-fiber-73 message="" cause="Exception in thread "zio-fiber-73" io.netty.handler.codec.PrematureChannelClosureException: channel gone inactive with 1 missing response(s)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:333)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at reproducer.ReproducerShortIdleTimeout.run.appLogic.routes(Reproducer.scala:24)
	at reproducer.ReproducerShortIdleTimeout.run.appLogic.routes(Reproducer.scala:28)
	at reproducer.ReproducerShortIdleTimeout.run.appLogic.routes(Reproducer.scala:29)
	at reproducer.ReproducerShortIdleTimeout.run.appLogic.routes(Reproducer.scala:33)
	at reproducer.ReproducerShortIdleTimeout.run.appLogic.routes(Reproducer.scala:34)
	at reproducer.ReproducerShortIdleTimeout.run.appLogic.routes(Reproducer.scala:35)" location=reproducer.ReproducerShortIdleTimeout.run.appLogic.routes file=Reproducer.scala line=32
```

### PR DESCRIPTION
**Pull request by kyri-petrou**
Opening this as a separate PR since it contains some rather big changes.

Some time ago, [I worked on an issue](https://github.com/zio/zio-http/pull/2610/files) where the client would hang on unexpected channel closures. While it seems the approach worked well till pretty much now, there are some underlying race condition between the channel closing and promises being fulfilled which seem to be present only when trying to update to ZIO 2.1.x (see [CI failure](https://github.com/zio/zio-http/actions/runs/9062096631/job/24895224533?pr=2840#step:9:11345)).

I'm still not 100% sure on why this issue is guaranteed to occur in ZIO 2.1.x, but the fix is to "unsafely" fulfil the promises instead of doing that via effects. A speculation is that it might be related to fork/join being much faster in ZIO 2.1.x, and therefore the "wrong" side of the race condition now almost always wins; although that's very hard to prove.

In either way, I rewrote all the client handlers to work without the need to run ZIO effects. This should end up being much more performant as we no longer need to create fibers just to fulfil promises, but also easier to follow and reason with.

PS: I know the handler API changes were not necessary, but I think it's better not to pass the `NettyRuntime` unnecessarily to the handlers. I hope this discourage the previous pattern of unnecessarily running effects in them

### CODE REVIEW

File: zio-http/jvm/src/main/scala/zio/http/netty/client/NettyClientDriver.scala [hunk 1]
```diff
@@ -155,26 +150,28 @@ final case class NettyClientDriver private[netty] (
...
+        ZIO.succeedUnsafe { implicit u =>
+          channel.closeFuture().addListener { (_: ChannelFuture) =>
+            // If onComplete was already set, it means another fiber is already in the process of fulfilling the promises
+            // so we don't need to fulfill `onResponse`
+            nettyRuntime.unsafeRunSync {
+              ZIO.whenZIO(onComplete.interrupt)(
+                onResponse.fail(
+                  new PrematureChannelClosureException(
+                    "Channel closed while executing the request. This is likely caused due to a client connection misconfiguration",
+                  ),
```
Comment (kyri-petrou) [inline zio-http/jvm/src/main/scala/zio/http/netty/client/NettyClientDriver.scala:166]: This change is not strictly necessary but I think adding a listener to Netty's `CloseFuture` is a much cleaner approach than forking an interruptible effect like previously

**Comment by kyri-petrou** [comment]
I just realised, this probably also /closes #2841

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
Nice work, @kyri-petrou!
