### PR TITLE
Fix: Do not escape valid headers

### LINKED ISSUE #1457: Incorrect header encoding
**Describe the bug**
https://github.com/zio/zio-http/pull/1409 broke the encoding of valid headers

**To Reproduce**
```
Headers("Access-Control-Allow-Methods", "POST, GET, OPTIONS").encode
```
**Expected**
```
Access-Control-Allow-Methods: POST, GET, OPTIONS
```

**Actual encoding**
```
Access-Control-Allow-Methods: "POST, GET, OPTIONS"
```

### PR DESCRIPTION
**Pull request by adwells-ds**
Fixes https://github.com/zio/zio-http/issues/1457

### CODE REVIEW

**Review by jdegoes — APPROVED** [review]

File: zio-http/src/test/scala/zio/http/service/ServerSpec.scala [hunk 1]
```diff
@@ -274,6 +275,12 @@ object ServerSpec extends HttpRunnableSpec {
           actual <- Http.response(res).deploy.headerValue(HeaderNames.vary).run()
         } yield assert(actual)(isSome(equalTo(expectedValue)))
       },
+      test("header with multiple values should not be escaped") {
+        val headers               = Headers("Access-Control-Allow-Methods", "POST, GET, OPTIONS")
+        val expected: HttpHeaders =
+          new DefaultHttpHeaders(true).add("Access-Control-Allow-Methods", "POST, GET, OPTIONS")
+        assertTrue(headers.encode == expected)
+      },
```
Comment (tusharmath) [inline zio-http/src/test/scala/zio/http/service/ServerSpec.scala]: Move the test to headerspec.

Comment (adwells-ds) [reply zio-http/src/test/scala/zio/http/service/ServerSpec.scala]: Moved

**Review by jdegoes — APPROVED** [review]

**Review by tusharmath — APPROVED** [review]
