### PR TITLE
Fix: Multipart Boundary Generation to Comply with RFC 2046

### LINKED ISSUE #3117: Multipart boundary generated by Body.fromMultipartFormUUID cannot be parsed by server
Have an ZClient calling another zio-http server endpoint with a multipart form and a auto-generated boundary:

```
body <- Body.fromMultipartFormUUID(
      Form(
        FormField.Simple("name", name),
        FormField.streamingBinaryField("upload", upload, MediaType.application.`octet-stream`, None, Some(fileName)),
      )
)
```

This generates a boundary of '(((random-uuid)))'. Passing this request with this boundary format is not parsed correctly by the zio-http server at the other end. I get an error:

```
400 POST /api/attachments 1194ms
timestamp=2024-09-09T22:58:40.380718Z level=INFO thread=#zio-fiber-940828076 message="Http request served" location=XXX.Main.run file=Main.scala line=81 method=POST duration_ms=1134 url=/api/attachments response_size=126 status_code=400 response="{"name":"MalformedBody","message":"Malformed request body failed to decode: Missing multipart/form-data field (Success(name)"}" content-type="multipart/form-data; boundary=(((71126f2f-0619-41dc-8914-86b0a1b318f0)))"
```

If I specify my own boundary value (i.e. --random-uuid), it works ok.

### PR DESCRIPTION
**Pull request by varshith257**
This PR addresses issue #3117, where multipart form boundaries generated by `Boundary.randomUUID` were not compliant with RFC 2046. The previous boundary format included invalid characters like parentheses `(((random-uuid)))` which caused server-side parsing errors and resulted in `400 Bad Request` responses.

### Changes
- Updated the `Boundary.randomUUID` method to generate RFC 2046-compliant boundaries by sanitizing the UUID. Any non-alphanumeric characters are replaced with hyphens (`-`), and the boundary is prefixed and suffixed with `----` to ensure a valid format.
- Added tests in `BoundarySpec.scala` to ensure the generated boundaries are valid and compliant with the standard.

fixes #3117
/claim #3117

### CODE REVIEW

File: zio-http/shared/src/main/scala/zio/http/Boundary.scala [hunk 1]
```diff
@@ -75,6 +75,6 @@ object Boundary {
 
   def randomUUID(implicit trace: Trace): zio.UIO[Boundary] =
     zio.Random.nextUUID.map { id =>
-      Boundary(s"(((${id.toString()})))")
+      Boundary(s"----${id.toString.replaceAll("[^a-zA-Z0-9]", "-")}----")
```
Comment (narma) [inline zio-http/shared/src/main/scala/zio/http/Boundary.scala]: UUID already conforms to `[a-zA-Z0-9-]`, no need to do this replace.

**Review by narma — CHANGES_REQUESTED** [review]

File: zio-http/shared/src/main/scala/zio/http/Boundary.scala (hunk 1 above)
Comment (asr2003) [inline zio-http/shared/src/main/scala/zio/http/Boundary.scala]:
```suggestion
      Boundary(s"----${id.toString}----")
```

**Review by asr2003 — CHANGES_REQUESTED** [review]

**Review by asr2003 — APPROVED** [review]

**Review by 987Nabil — APPROVED** [review]
