### PR TITLE
Mark `application/json` as NotBinary (#2752)

### LINKED ISSUE #2752: Endpoint API: Java ClassCastException when Using ZIO HTTP Streaming
**Describe the bug**
Encountered a `ClassCastException` in ZIO HTTP's streaming endpoint

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the following HTTP app:

```scala
import zio._
import zio.http._
import zio.http.endpoint.Endpoint
import zio.http.endpoint.EndpointMiddleware.None
import zio.schema.DeriveSchema
import zio.schema.codec.JsonCodec.schemaBasedBinaryCodec
import zio.stream.ZStream

object EndpointWithStreamingOutput extends ZIOAppDefault {
  case class Event(msg: String)

  object Event {
    implicit val schema = DeriveSchema.gen[Event]
  }

  val endpoint: Endpoint[Unit, Unit, ZNothing, ZStream[Any, Nothing, Event], None] =
    Endpoint(RoutePattern.GET / "events")
      .outStream[Event]

  val streamingHandler: Handler[Any, ZNothing, Unit, ZStream[Any, Nothing, Event]] =
    Handler.succeed(
      ZStream.from(Chunk(1, 2, 3).map(_.toString).map(Event(_)))
    )

  val app = endpoint.implement(streamingHandler).toHttpApp @@ Middleware.debug

  def run = Server.serve(app).provide(Server.default, Scope.default)

}
```
2. run this curl command: ` curl -X 'GET'  'http://127.0.0.1:8080/events'`

**Expected behaviour**
I expect the curl method to return events properly

**Current Behaviour**
The app throws the following exception:

```scala
timestamp=2024-03-29T11:06:33.973217Z level=INFO thread=#zio-fiber-4 message="Starting the server..." location=example.endpoint.EndpointWithStreamingOutput.run file=EndpointWithStreamingOutput.scala line=29
timestamp=2024-03-29T11:06:33.984464Z level=INFO thread=#zio-fiber-4 message="Server started" location=example.endpoint.EndpointWithStreamingOutput.run file=EndpointWithStreamingOutput.scala line=29
200 GET /events 80ms
Mar 29, 2024 3:36:38 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.ClassCastException: class example.endpoint.EndpointWithStreamingOutput$Event cannot be cast to class java.lang.Byte (example.endpoint.EndpointWithStreamingOutput$Event is in unnamed module of loader 'app'; java.lang.Byte is in module java.base of loader 'bootstrap')
	at scala.runtime.BoxesRunTime.unboxToByte(BoxesRunTime.java:91)
	at scala.runtime.ScalaRunTime$.array_update(ScalaRunTime.scala:80)
	at scala.Array$.slowcopy(Array.scala:86)
	at scala.Array$.copy(Array.scala:112)
	at zio.Chunk$Arr.toArray(Chunk.scala:1727)
	at zio.Chunk.toArray(Chunk.scala:1002)
	at zio.Chunk.toArray(Chunk.scala:873)
	at zio.http.netty.NettyBodyWriter$.$anonfun$writeAndFlush$14(NettyBodyWriter.scala:123)
	at zio.http.netty.NettyFutureExecutor$.$anonfun$make$1(NettyFutureExecutor.scala:67)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:904)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:948)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1024)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1024)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1024)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:967)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:890)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1024)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1024)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:381)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:504)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:220)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:139)
	at zio.internal.ZScheduler$$anon$4.run(ZScheduler.scala:478)
```

### PR DESCRIPTION
**Pull request by guersam**
/fix #2752

#899 marked `application/json` as binary, but it seems to be a mistake considering the other JSON variants are marked as not binary.

### CODE REVIEW

**Comment by guersam** [comment]
Some tests are failing. Maybe it was intentional, or there are some other functions that are depending on the false assumption.

File: zio-http/shared/src/main/scala/zio/http/codec/HttpContentCodec.scala [hunk 1]
```diff
@@ -193,7 +193,7 @@ object HttpContentCodec {
       ZPipeline.identity[Chunk[Byte]].flattenChunks
   }
 
-  val byteChunkCodec: HttpContentCodec[Chunk[Byte]] = {
+  implicit val byteChunkCodec: HttpContentCodec[Chunk[Byte]] = {
     HttpContentCodec(
       ListMap(
         MediaType.allMediaTypes.filter(_.binary).map(mt => mt -> ByteChunkBinaryCodec): _*,
```
Comment (guersam) [inline zio-http/shared/src/main/scala/zio/http/codec/HttpContentCodec.scala:199]: Given the order of the codecs matter, I wonder if `application/octet-stream` should come first here.

File: zio-http/shared/src/main/scala/zio/http/codec/HttpContentCodec.scala [hunk 2]
```diff
@@ -216,7 +216,7 @@ object HttpContentCodec {
       ZPipeline.identity[Byte]
   }
 
-  val byteCodec: HttpContentCodec[Byte] = {
+  implicit val byteCodec: HttpContentCodec[Byte] = {
     HttpContentCodec(
       ListMap(
         MediaType.allMediaTypes.filter(_.binary).map(mt => mt -> ByteBinaryCodec): _*,
```
Comment (guersam) [inline zio-http/shared/src/main/scala/zio/http/codec/HttpContentCodec.scala:222]: Same as the above

File: zio-http/shared/src/main/scala/zio/http/codec/HttpContentCodec.scala (hunk 1 above)
Comment (987Nabil) [reply zio-http/shared/src/main/scala/zio/http/codec/HttpContentCodec.scala:199]: I don't think so. I think it is like this. If you do not explicitly declare a media type, the accept header of the client should decide. That is the case already. If you want to return only `application/octet-stream`, then you have to make this explicit in the endpoint definition.

**Review by jdegoes — APPROVED** [review]

File: zio-http/shared/src/main/scala/zio/http/codec/HttpContentCodec.scala (hunk 2 above)
Comment (guersam) [reply zio-http/shared/src/main/scala/zio/http/codec/HttpContentCodec.scala:222]: @987Nabil FYI: I remember you were skeptical of having the primitive codecs implicit. Please consider these changes are merged as they are when you redesign the codecs.
