### PR TITLE
Fix: Content-Length issues

### LINKED ISSUE #641: Encoding problem when using HttpData.fromText and multi byte characters
HttpData.unsafeSize for Text returns number of characters and not bytes. This results in a bad content length and a broken response when using multi byte characters like e.g. `åäö`.

Current work around:

Instead of
`HttpData.fromText("åäö")` or `Response.text("åäö")`

do 
`HttpData.fromByteBuf(Unpooled.copiedBuffer("åäö", HTTP_CHARSET))`

Version: 1.0.0.0-RC18

### PR DESCRIPTION
**Pull request by tusharmath**
fixes #641 #679

### CODE REVIEW

File: zio-http/src/test/scala/zhttp/service/ServerSpec.scala [hunk 1]
```diff
@@ -157,13 +159,25 @@ object ServerSpec extends HttpRunnableSpec(8088) {
...
+            }
+        }
       }
   }
 
   override def spec = {
     suiteM("Server") {
       app.as(List(staticAppSpec, dynamicAppSpec, responseSpec, requestSpec)).useNow
-    }.provideCustomLayerShared(env) @@ timeout(30 seconds) @@ sequential
+    }.provideCustomLayerShared(env) @@ timeout(3000 seconds) @@ sequential
```
Comment (amitksingh1490) [inline zio-http/src/test/scala/zhttp/service/ServerSpec.scala]: Do we need this change?

File: zio-http/src/main/scala/zhttp/service/Handler.scala [hunk 2]
```diff
@@ -154,29 +138,10 @@ private[zhttp] final case class Handler[R](
...
-
-            case data @ HttpData.BinaryChunk(_) =>
-              unsafeWriteLastContent(data.encodeAndCache(res.attribute.memoize))
-              releaseRequest(jReq)
-
-            case HttpData.BinaryStream(stream) =>
-              unsafeRunZIO(
-                writeStreamContent(stream) *> Task(releaseRequest(jReq)),
-              )
+            case HttpData.BinaryStream(stream) => unsafeRunZIO(writeStreamContent(stream) *> Task(releaseRequest(jReq)))
```
Comment (amitksingh1490) [inline zio-http/src/main/scala/zhttp/service/Handler.scala:143]: This might introduce a memory leak when writeStreamContent fails `releaseRequest(jReq)` might not get called. But this is still there in main, We can ignore this for now, but can we  add a todo here.

Comment (tusharmath) [reply zio-http/src/main/scala/zhttp/service/Handler.scala:143]: Yes, you are right. I think this issue is there even in the current main.

**Review by amitksingh1490 — APPROVED** [review]

File: zio-http/src/main/scala/zhttp/service/Handler.scala (hunk 2 above)
Comment (amitksingh1490) [reply zio-http/src/main/scala/zhttp/service/Handler.scala:143]: I will raise an separate issue for this

**Review by amitksingh1490 — APPROVED** [review]
