### PR TITLE
Fix Backpressure Example

### LINKED ISSUE #545: BUG: ContentDecoder.Text not working as expected in release/next
While writing an integration test case for text content decoder, it was found that the functionality doesn't work as expected in release/next. This can also be verified by running the Backpressure.scala example, hitting the endpoint **/foo**, and sending a text string as data

# Steps to replicate
* Checkout to release/next
* Run Backpressure.scala
* Run the following command
```shell
curl -i --request POST http://localhost:8090/foo --data 'This is a string'
```

https://user-images.githubusercontent.com/21025968/142822872-0e14c143-8803-48a6-96ff-346326778ee2.mov

### PR DESCRIPTION
**Pull request by ShrutiVerma97**
fixes #545

### CODE REVIEW

File: zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala [hunk 1]
```diff
@@ -38,6 +39,11 @@ final case class ServerChannelInitializer[R](
     // Add Keep-Alive handler is settings is true
     if (cfg.keepAlive) pipeline.addLast(HTTP_KEEPALIVE_HANDLER, new HttpServerKeepAliveHandler)
 
+    // FlowControlHandler
+    // Required because HttpObjectDecoder fires an HttpRequest that is immediately followed by a LastHttpContent event.
+    // For reference: https://netty.io/4.1/api/io/netty/handler/flow/FlowControlHandler.html
+    pipeline.addLast(FLOW_CONTROL_HANDLER, new FlowControlHandler())
```
Comment (tusharmath) [inline zio-http/src/main/scala/zhttp/service/server/ServerChannelInitializer.scala]: make it configurable defaulting to true.

File: zio-http/src/main/scala/zhttp/service/Server.scala [hunk 2]
```diff
@@ -26,6 +26,7 @@ sealed trait Server[-R, +E] { self =>
     case Address(address)     => s.copy(address = address)
     case AcceptContinue       => s.copy(acceptContinue = true)
     case KeepAlive            => s.copy(keepAlive = true)
+    case FlowControl          => s.copy(flowControl = false)
```
Comment (ShrutiVerma97) [inline zio-http/src/main/scala/zhttp/service/Server.scala:29]: Should I change the name to `FlowControlHandler`?
